---
# Ingresses for Kong API Gateway to talk to the Admin APIs
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: monitoring-rewrite
config:
  add:
    headers:
      - x-new-header:newvalue
  replace:
    uri: "/$(uri_captures[1])"
plugin: request-transformer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring
  annotations:
    kubernetes.io/ingress.class: kong
    # konghq.com/strip-path: "true"
    konghq.com/plugins: monitoring-rewrite
spec:
  rules:
    - http:
        paths:
          - path: /monitoring/grafana/(.*)
            backend:
              serviceName: promfana-grafana
              servicePort: 80
          - path: /monitoring/elasticsearch/(.*)
            backend:
              serviceName: elasticsearch-master
              servicePort: 9200
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: kibana.beta.moja-lab.live
      http:
        paths:
          - path: /
            backend:
              serviceName: efk-kibana
              servicePort: 5601