# TODO: templatize this chart!
# for now, this is deployable as unomfi only
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unomfi-simulator
  labels:
    app: unomfi-simulator
    app.kubernetes.io/name: unomfi-simulator
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # exeed the replicas by 1 pod
  selector:
    matchLabels:
      app: unomfi-simulator
  template:
    metadata:
      labels:
        app: unomfi-simulator
    spec:
      volumes:
        - name: unomfi-simulator-volume
          secret:
            secretName: unomfi-simulator-secret
      containers:
        - name: unomfi-simulator
          image: mojaloop/contrib-firebase-simulator:v0.2.20
          # command: ["tail", "-f", "/dev/null"]
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 30
            httpGet:
              path: /app/health
              port: 8080
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 30
            httpGet:
              path: /app/health
              port: 8080
          env:
            # need to bind to 0.0.0.0 for kubernetes to be able to expose this service 
            - name: IP_ADDRESS
              value: "0.0.0.0"
            - name: PARTICIPANT_ID
              value: "unomfi"
            - name: READABLE_PARTICIPANT_NAME
              value: "UnoMFI"
            - name: BASE_PATH
              value: "/unomfi"
            - name: SHOULD_SEND_LIVE_SMS
              value: "true"
            - name: PUBLIC_FIREBASE_CONFIG
              value: '{"apiKey":"AIzaSyAj9m32nSl5J_XdsOdU37Kwy4JEShEhxUU","authDomain":"unomfi-simulator.firebaseapp.com","projectId":"unomfi-simulator","storageBucket":"unomfi-simulator.appspot.com","messagingSenderId":"526639962800","appId":"1:526639962800:web:eaca447f949c64305ef975"}'
            - name: DEMO_CURRENCY
              value: "PHP"
          envFrom:
            - secretRef:
                name: twilio-env
          volumeMounts:
            - name: unomfi-simulator-volume
              mountPath: "/opt/contrib-firebase-simulator/config/serviceAccountKey.json"
              subPath: serviceAccountKey.json

---
apiVersion: v1
kind: Service
metadata:
  name: unomfi-simulator
spec:
  ports:
    - port: 8080
      name: ui
  selector:
    app: unomfi-simulator
  clusterIP: None

