---
# Ingresses for Kong API Gateway to talk to the Admin APIs
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: admin-rewrite
config:
  add:
    headers:
      - x-new-header:newvalue
  replace:
    uri: "/$(uri_captures[1])"
plugin: request-transformer
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: user123
  annotations:
    kubernetes.io/ingress.class: kong
username: harry 
credentials:
  - harry-basicauth
---
apiVersion: v1
kind: Secret
metadata:
  name: user123-key
stringData:
  username: user123
  kongCredType: basic-auth
  password: OpenSesame
---
# KongPlugin for basic auth - for the demo we can just configure this manually and provide to users
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: basic-auth-example
plugin: basic-auth
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: admin
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: admin-rewrite
    # TODO: if you want to implement auth tokens - start here!
    # konghq.com/plugins: admin-rewrite, basic-auth-example
spec:
  rules:
    - http:
        paths:
          - path: /api/admin/central-ledger/(.*)
            backend:
              serviceName: mojaloop-centralledger-service
              servicePort: 80
          - path: /api/admin/account-lookup-service/(.*)
            backend:
              serviceName: mojaloop-account-lookup-service
              servicePort: 80
          - path: /api/admin/account-lookup-service-admin/(.*)
            backend:
              serviceName: mojaloop-account-lookup-service-admin
              servicePort: 80
          - path: /api/admin/ml-api-adapter/(.*)
            backend:
              serviceName: mojaloop-ml-api-adapter-service
              servicePort: 80
          - path: /api/admin/oracle-simulator/(.*)
            backend:
              serviceName: mojaloop-simulator
              servicePort: 80
          - path: /api/admin/quoting-service/(.*)
            backend:
              serviceName: mojaloop-quoting-service
              servicePort: 80
         