
apiVersion: extensions/v1beta1 
kind: Ingress
metadata:
  name: ingress-figmm
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    # Deprecated - keping for backwards compatability
    - host: figmm.beta.moja-lab.live
      http:
        paths:
          - path: /api
            backend:
              serviceName: figmm-ml-testing-toolkit-backend
              servicePort: 5050 
          - path: /
            backend:
              serviceName: figmm-ml-testing-toolkit-frontend
              servicePort: 6060
          - path: /socket.io/
            backend:
              serviceName: figmm-ml-testing-toolkit-backend
              servicePort: 5050

    - host: figmm.sandbox.mojaloop.io
      http:
        paths:
          - path: /api
            backend:
              serviceName: figmm-ml-testing-toolkit-backend
              servicePort: 5050 
          - path: /
            backend:
              serviceName: figmm-ml-testing-toolkit-frontend
              servicePort: 6060
          - path: /socket.io/
            backend:
              serviceName: figmm-ml-testing-toolkit-backend
              servicePort: 5050
    
    - host: figmm-backend.sandbox.mojaloop.io
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: figmm-ml-testing-toolkit-backend
              servicePort: 5000
